sudo: false

language: ruby

env:
  global:
    secure: "Ws7ZIJ/cpOkf76mY97IKpmAE1hbJX8btyAdk91QoSR4gYW6cT8A8b4LQ3zZ5tA0ANYIUnlv/c30JMlI2UZDlphjwhWcAaZRZT2HMHfDNaxjiUgAA7rshLbne7dAJrFnWQQPmdDhPEKEEDXbCU/kTjf254ivqTTtNpgI+EKIxSTJWkD4eW6CcOcvEFGBKZxGXZsk2ntnXxSr/OWdRtu1Symlz080jA3G8kb4dqwICz2vab1f3irD5xEmY6a+1I09nK/LvnmZKAWGdGghHs5tVYik6rqa6dPQ1NIJkPv3Y+ou73vCUOrkyalAcUD0x3obySRZnu4xf8bOZibkf+7LcWq4ZoLJe1Sa6SP+K6kaccRHBRHOIQ5LOvjiQjiVXyyBLH6rbtldzwmqBc4ULFNprnbcXsjEzY5FfxSGmRdBSfRGedlzc1ALseVMLIdSJR4Bd5+/GxZPMLnjzveYt7/xofNhnFpnoaGhmpz1IpHm61/pnrP5aIUpYevdP9AeRZshqAK2AD4W7dtp6NU6cnug+DQgdARqGHmHWK95rD+4Z6QAR0uNcpjeiq05S+c9zdpvYNIBUgMrBFUHojAKKT2tds2GksXo+d5JWUJ8748ncFwfEEojXlgS7dWuU3r6SNNQHo3twknzWfoXySOru9rkJwRAPiZBJvefm2aoKGFiqQCY="
    secure: "CLkKnY/ip4nqBVihDK2v5NtwJc5gsa0d86JOtpkgxw2fsmDK3gwBAoDNQN8/5WdY2oQfMCbXXcibTIsLZMrGqKAsguOAKJVB2CkGqisreYS/AgBiMaFriwf06zQY3RUOTx2V4BBKJWZK/aFh0P7TP0vRurqswomejxLFZZBl4F0n58Bu/1YONYDiOoDCla6hLHn19iQyKmxv+7ZSfTd+19bEhjmmQsfUivcOoBb7t7WMrVU0PxnmUhlHpbn5RjRq1XFXkQr2Wx0sOBAM6JrvucA04GVSJgmEl1XzCW3vBNfpp1/X8dQrVAjbhCjy8Ao9XBTZG3Exc/kOYf2TxEBMOXzuTZPsx6O7URHk6YSySrs1SOqKloSXggw87541L+fsZthCNCx8oENqsJyPRIZaFZV8WhVe20v6Tvz/UPNi9lzPvpgbdURYBON2gJGwMuBy2gF/CKGzbkxfPim7e273+utmrz3j1Frm0h+eZ7BL706XktrWRFxzn7OHrSuZM6WfRu0QgR15CVqTOeSTWZuk5fylt42tbdF88dVDsuRgrYZ0Kbl/gyP0fw2MnrE/rJiXZ1ADMH/6EG+6AA9Dban/PnmIOwKenGLsa0eiGYIPf8kL2VXakHzcmdRjRdeSfZAGaN+fARGNVStYJXc0oK1YozyVahKzVX7J7tDbKDZ+Gqk="
    secure: "HzpEHx5Opf74Sgy85H5hhTPNMEKv0MmLddxbVYHlhAIBhNQEVMQlf8HX7tH9XN/tkkzgJX+/+BMBHLeYw4r2Ex3fpB7Mh7HfJB1JjEpzRQ052wTB9hpn+hUuWb68l+V2OGb8ZGKTi4WmXb6QCPJgPORZPrpU06jAhlNW1ocP1YsIYDb4XyeRy9GF7NCpnDkM12NDGvI/c7nctI4NmasH2A6KTjMJoVfNoEuJWRB9hKI2m6hBEtOw1Ls8/PU57Dsp6YsPMg+yMgKiqypAtu+y0U2RZk1l5SMszmmUPnPvHLzdqXYGCdAtDVrX06Ja4YubMUihVen7dpqJtIcna1oLyUkqFy7OcIKKY/TpE4vr6ySDAZbC975+4UDT2HuW5Gn5PxKaMaQivf4bLHMGnK3lrl/Mhg25lD42i1eTg2sKXuZKAuZurLVUTfpNDHh8BWZVyF4a/Bw1ubZnfxPJD79G5BpW4c9I/+/i4k3w9ATPvtUjEpZXqvStdxfQReu5luSQsQDNDnKMlc3x/OSehflZvd8UarUv+uSDAQ9Y6ZL61MIKV5OsF2jOic6ZW1519+3Nh9Ik6ECfEItJb9uNdvLWj85l3obnWrCkuEXKS3fHADcfgHFxk06mcEZ5jvS1Tjrf/eR5/qmrlooFBe1ktAwTent3Fgw4/67Vq4EX1oNIl9M="

install:
  - npm install

script:
  - bundle install
  - ./node_modules/.bin/gulp

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master

notifications:
  slack:
    secure: zes7bl+WKgHlV9v0tFXNXQ8AQGVk+pleyYL/VOsHPGY3AYQaQVgSurFXXNZ4dWFwOQi2XBqr6j1NWQN3Rluou+VkCPhxbGOeKQaA6jBnVztk0ycv30itAaIC7Id+HEo6/aekk9q8be2/cX/fHLUqS21ySgo+k4stTPlvUrgvOYWBLvDikBNL9L/HkF+D1Pe+nrFUgDNwRfP5nprGqBFXbid6CHrpCYWgkNZljX+nzriteMQ/JzzTOh/VamJHvu4d9WzsTXuWvaEnJGU4yjKVFgRCOwF10HgR7Ljlxjv9Gng1iwE7L/+3CTV72GBV5o4AlgVsVlKMpmKV+xyNiKSMyMPutTcskIw+ANv5haU/Dw//3Yt7vxtfAwmQtlrHUUKakEK+pGSBShr7MZRZIj/PEWO/DoyIF3BxIjiBvSsI5ppiJCNZ2Sn8kopfiYhzjzG/HrKjHhrZADJ3szogbqQlYQ6QwZ2yOVHk/6rMSb/0R72dO91+DOKptBb1bDDiBgwYgDDsf7MFzHX9PxjLTyuGfaWtNGmkTQkN2dx0hw6AyNYzI2VgTlKsb4sNtOR+C8xJ9zTkLxoFl4hsAhOtIdK5qy2iewlIw7ylxF33pjiQYkIqCLekuYM/RIJbzQzVLilCjqu11cnKUXr14Pu/Y/St151dpMoRnQWzhxUTk1HKx1o=
    on_success: change
    on_failure: always
    on_start: never
  email: false
